# Group6-Homework 
Haijing ZHU,Ting ZHU,Huajuan ZHOU,You SHAN,Zhen XING

# Exercise 1 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

C:\Users\00\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [3]:
erf = pd.read_csv('https://github.com/QuantEcon/ShenzhenWinterCamp/raw/master/Jiao%20Shi/ER_predict.csv')
erf

Date  CNYUSD  RMB_REER  CHN PMI  USA PMI       CHN M1     USA M1  \
0    2005-07  8.1062     85.01     51.1     52.8   97,700.00   1,365.00    
1    2005-08  8.0998     85.05     52.6     52.4   99,400.00   1,376.50    
2    2005-09  8.0920     85.29     55.1     56.8  101,000.00   1,363.10    
3    2005-10  8.0845     86.39     54.1     57.2  101,800.00   1,365.10    
4    2005-11  8.0804     87.75     54.1     56.7  104,100.00   1,373.20    
5    2005-12  8.0702     87.59     54.3     55.1  107,300.00   1,396.90    
6    2006-01  8.0608     86.88     52.1     55.0  107,400.00   1,375.20    
7    2006-02  8.0415     88.13     52.1     55.8  104,400.00   1,361.70    
8    2006-03  8.0170     86.90     55.3     54.3  107,000.00   1,394.40    
9    2006-04  8.0165     85.98     58.1     55.2  106,400.00   1,393.30    
10   2006-05  8.0188     83.76     54.8     53.7  109,200.00   1,391.80    
11   2006-06  7.9956     84.45     54.1     52.0  112,300.00   1,378.70    
12   2006-07  7.9732     84.22     52.4     53.0  112,700.00   1,368.20    
13   2006-08  7.9585     84.12     53.1     53.7  114,800.00   1,370.20    
14   2006-09  7.9087     85.45     57.0     52.2  116,800.00   1,347.00    
15   2006-10  7.8792     86.23     54.7     51.4  118,400.00   1,359.90    
16   2006-11  7.8436     86.22     55.3     50.3  121,600.00   1,368.10    
17   2006-12  7.8087     86.53     54.8     51.4  126,000.00   1,387.30    
18   2007-01  7.7776     88.38     55.1     49.5  129,000.00   1,368.60    
19   2007-02  7.7409     89.59     53.1     51.9  126,000.00   1,347.00    
20   2007-03  7.7342     88.16     56.1     50.7  127,900.00   1,377.90    
21   2007-04  7.7055     87.07     58.6     52.6  128,000.00   1,391.80    
22   2007-05  7.6506     87.66     55.7     52.5  130,300.00   1,385.10    
23   2007-06  7.6155     88.62     54.5     52.6  135,800.00   1,370.20    
24   2007-07  7.5737     88.94     53.3     52.4  136,200.00   1,368.10    
25   2007-08  7.5607     89.88     54.0     50.9  141,000.00   1,372.30    
26   2007-09  7.5108     89.64     56.1     51.0  142,600.00   1,355.80    
27   2007-10  7.4692     88.38     53.2     51.1  144,600.00   1,368.90    
28   2007-11  7.3997     88.48     55.4     50.5  148,000.00   1,370.00    
29   2007-12  7.3046     90.20     55.3     49.0  152,500.00   1,394.40    
..       ...     ...       ...      ...      ...          ...        ...   
120  2015-07  6.1172    131.03     50.0     52.7  353,100.00   3,037.80    
121  2015-08  6.3893    130.41     49.7     51.1  362,800.00   3,021.70    
122  2015-09  6.3613    130.22     49.8     50.2  364,400.00   3,015.70    
123  2015-10  6.3495    129.03     49.8     50.1  375,800.00   3,011.30    
124  2015-11  6.3962    131.02     49.6     48.6  387,600.00   3,055.60    
125  2015-12  6.4936    130.33     49.7     48.0  401,000.00   3,140.40    
126  2016-01  6.5516    129.75     49.4     48.2  412,700.00   3,093.70    
127  2016-02  6.5452    130.84     49.0     49.5  392,500.00   3,096.80    
128  2016-03  6.4612    128.61     50.2     51.8  411,600.00   3,180.60    
129  2016-04  6.4589    126.19     50.1     50.8  413,500.00   3,235.80    
130  2016-05  6.5790    125.14     50.1     51.3  424,300.00   3,236.70    
131  2016-06  6.6312    123.03     50.0     53.2  443,600.00   3,249.50    
132  2016-07  6.6511    121.78     49.9     52.6  442,900.00   3,247.80    
133  2016-08  6.6908    120.76     50.4     49.4  454,500.00   3,322.30    
134  2016-09  6.6778    121.16     50.4     51.5  454,300.00   3,300.20    
135  2016-10  6.7641    120.90     51.2     51.9  465,400.00   3,329.70    
136  2016-11  6.8865    121.60     51.7     53.2  475,400.00   3,325.90    
137  2016-12  6.9370    122.84     51.4     54.5  486,600.00   3,381.30    
138  2017-01  6.8588    123.29     51.3     56.0  472,500.00   3,378.80    
139  2017-02  6.8750    122.08     51.6     57.7  476,500.00   3,337.60    
140  2017-03  6.8993    120.42     51.8     57.2  488,80

## UIP

In [39]:
erf['lner'] = np.log(erf[['CNYUSD']])
erf['dep'] = 100*erf['lner'].diff(periods = 1)

In [40]:
erf['dep_1'] = 0
size_sample = 149
for i in range(size_sample):
    erf.loc[i,'dep_1'] = erf.loc[i+1,'dep']
erf.loc[size_sample,'dep_1'] = erf.loc[0,'dep']

In [41]:
erf['int_diff'] = erf['CHN_IBR'] - erf['US_FFR']
erf['const'] = 1

In [42]:
size_sample = 149
size_subsample = 60
fcst_int = np.zeros(size_sample - size_subsample)

for i in range (size_sample - size_subsample):
    reg_intsub = sm.OLS(endog=erf.loc[i:size_subsample-1+i,'dep_1'], exog=erf.loc[erf.index[i:size_subsample+i],['const', 'int_diff']], missing='drop')
    results_sub = reg_intsub.fit()
    fcst_int[i] = results_sub.predict(exog = [1, erf.loc[size_subsample+i,'int_diff']])
fcst_int

array([-0.08043075, -0.10854805, -0.09803472, -0.15282656, -0.16697509,
       -0.14718744, -0.12255059, -0.0950402 , -0.17351076, -0.21883391,
       -0.16328831, -0.12039438, -0.01508622, -0.19130606, -0.17706097,
       -0.10935742, -0.16554642, -0.20832904, -0.15765074, -0.19766922,
       -0.21597569, -0.20153545, -0.15779705, -0.24355509, -0.06709501,
       -0.14457581, -0.20979694,  0.00511567, -0.09885078, -0.19680745,
       -0.17591762, -0.17209116, -0.168597  , -0.19615056, -0.21244152,
       -0.30167516, -0.2688134 , -0.22243979, -0.20701868, -0.20665414,
       -0.24606571, -0.24893286, -0.21185834, -0.22898564, -0.17455395,
       -0.17305536, -0.17081097, -0.17484414, -0.16418102, -0.15834242,
       -0.1678851 , -0.17959862, -0.18355495, -0.18613438, -0.1359401 ,
       -0.16943076, -0.12905197, -0.16978528, -0.30716826, -0.3258962 ,
       -0.28030249,  0.04200635,  0.07205624,  0.0522032 ,  0.10612828,
        0.22123229,  0.26787995,  0.26686977,  0.20352729,  0.21

In [43]:
dire1 = np.zeros(size_sample - size_subsample) 
real = np.zeros(size_sample - size_subsample)
for i in range(size_sample - size_subsample):
    real[i] = erf.loc[size_subsample+i, 'dep_1']
    dire = real[i]*fcst_int[i]
    if dire > 0:
        dire1[i]=1
percentage1 = dire1.sum()/(size_sample - size_subsample)
percentage1       

0.6179775280898876

## The Taylor-rule model 

In [44]:
erf['inflation_diff'] = erf['CHN CPI inflation'] - erf['USA CPI inflation']
predict_tr = np.zeros(size_sample - size_subsample)
erf['const'] = 1
for i in range (size_sample - size_subsample):
    y_chn = erf['CHN PMI'] - np.mean(erf.loc[i:size_subsample-1+i, 'CHN PMI'])
    y_us = erf['USA PMI'] - np.mean(erf.loc[i:size_subsample-1+i, 'USA PMI'])
    erf['y_diff'] = y_chn - y_us
    
    reg_trsub = sm.OLS(endog=erf.loc[i:size_subsample-1+i,'dep_1'], exog=erf.loc[erf.index[i:size_subsample+i],['const', 'inflation_diff','y_diff']], missing='drop')
    results_sub = reg_trsub.fit()    
    predict_tr[i] = results_sub.predict(exog = [erf.loc[size_subsample+i,['const', 'inflation_diff','y_diff']]])
predict_tr    

array([-0.52833672, -0.45795418, -0.57053999, -0.6227859 , -0.67465758,
       -0.59244255, -0.60831188, -0.52044214, -0.48158751, -0.44592111,
       -0.42979174, -0.49432561, -0.52733906, -0.47697216, -0.44974361,
       -0.4236177 , -0.19119304, -0.24746514, -0.32413105, -0.10948334,
       -0.22267607, -0.24966314, -0.23092411, -0.10000886, -0.0759473 ,
       -0.03601506,  0.04994283,  0.08469451, -0.07449437, -0.16704285,
       -0.09275403, -0.20750194, -0.11517827, -0.22544126, -0.14909539,
       -0.18196498, -0.17497362, -0.2215353 , -0.29905663, -0.3319002 ,
       -0.28810137, -0.21183516, -0.16864857, -0.15962897, -0.14813121,
       -0.02136123, -0.08507225, -0.08355737, -0.09037968, -0.1160672 ,
       -0.05210565, -0.08909492, -0.13729001, -0.15872543, -0.13884597,
       -0.19567389, -0.17076181, -0.21250464, -0.16085442, -0.17555845,
       -0.18370616, -0.11591507, -0.08035114, -0.02259793,  0.04497651,
        0.18679695,  0.25986971,  0.08117044, -0.01777663,  0.04

In [45]:
dire2 = np.zeros(size_sample - size_subsample) 
real1 = np.zeros(size_sample - size_subsample)
for i in range(size_sample - size_subsample):
    real1[i] = erf.loc[size_subsample+i, 'dep_1']
    dire = real[i]*predict_tr[i]
    if dire > 0:
        dire2[i]=1
percentage2 = dire2.sum()/(size_sample - size_subsample)
percentage2       

0.6404494382022472

## the random walk model

In [46]:
dire3 = np.zeros(size_sample)
for i in range(size_sample):
    if erf.loc[i,'dep_1'] * erf.loc[i,'dep'] > 0:
        dire3[i]=1
percentage3 = dire3.sum()/size_sample
percentage3  

0.66442953020134232

# Exercise 2

In [47]:
erf['ee'] = np.log(erf[['RMB_REER']])
erf['dep'] = 100*erf['ee'].diff(periods = 1)

In [48]:
erf['dep_2'] = 0
size_sample = 149
for i in range(size_sample):
    erf.loc[i,'dep_2'] = erf.loc[i+1,'dep']
erf.loc[size_sample,'dep_2'] = erf.loc[0,'dep']

In [49]:
erf['inflation_diff'] = erf['CHN CPI inflation'] - erf['USA CPI inflation']

for i in range (size_sample):
    y_chn = erf['CHN PMI'] - np.mean(erf.loc[i:size_subsample-1+i, 'CHN PMI'])
    y_us = erf['USA PMI'] - np.mean(erf.loc[i:size_subsample-1+i, 'USA PMI'])
    erf['y_diff'] = y_chn - y_us

In [50]:
erf['constant'] = 1
reg = sm.OLS(endog=erf['dep_2'], exog=erf[['constant', 'inflation_diff','y_diff']], missing='drop')
results = reg.fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                  dep_2   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                 -0.006
Method:                 Least Squares   F-statistic:                    0.5306
Date:                Fri, 02 Feb 2018   Prob (F-statistic):              0.589
Time:                        19:55:26   Log-Likelihood:                -254.66
No. Observations:                 149   AIC:                             515.3
Df Residuals:                     146   BIC:                             524.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
constant           0.4019      0.197      2.

In [51]:
size_subsample = 60
error_tr2 = np.zeros(size_sample - size_subsample)
for i in range (size_sample - size_subsample):
    reg_trsub = sm.OLS(endog=erf.loc[i:size_subsample-1+i,'dep_2'], exog=erf.loc[erf.index[i:size_subsample+i],['const', 'inflation_diff','y_diff']], missing='drop')
    results_sub = reg_trsub.fit()
    error = results_sub.predict(exog = [erf.loc[size_subsample+i,['const', 'inflation_diff','y_diff']]])-erf.loc[size_subsample+i, 'dep_2']
    error_tr2[i] = error  
error_tr2                                                                                                                 

array([  1.80709232e+00,   6.87011382e-01,   1.94411743e+00,
        -1.53336823e+00,  -7.48185728e-01,   2.34123399e-01,
         1.34337894e-01,   2.19657122e+00,   1.62692389e+00,
         1.99572239e-01,  -2.57749582e-03,   9.73117248e-03,
        -5.71111920e-01,  -2.84842505e+00,  -8.40349424e-01,
        -2.41001186e-01,  -9.84682029e-01,  -8.53057381e-01,
         1.85760303e+00,   2.57742381e-01,   5.66704033e-01,
        -3.93451078e-01,   6.65190409e-01,   5.53397852e-01,
         8.56878134e-01,   1.27077916e+00,   2.24269420e-01,
        -1.32678687e+00,   1.00885301e-01,  -1.00650173e+00,
        -1.21080217e+00,   1.34020172e-01,  -5.51936086e-01,
        -5.09333416e-01,   3.28919954e-01,  -3.36949195e-01,
         6.02206172e-01,   2.88427369e-01,   1.49947646e+00,
        -8.21831851e-01,  -4.22748041e-01,  -1.44097019e+00,
         3.32742177e-01,   3.47194433e+00,   2.71311579e+00,
         1.18098253e+00,   3.03815319e-01,  -4.50504091e-01,
        -1.72887903e+00,

In [52]:
rmse_tr = np.sqrt(np.mean(error_tr2**2))
rmse_tr

1.2349671429422964