# Group 1 Assignment
## Members: Yang LI, Yuwen CHE, Yi LIANG, Yun LI, Xiaoyi HAO, Hemin HE

### Additional Exercise 1

In [14]:
import numpy as np

x=np.random.randn(1000000)
print(x)

[-1.79232734  0.5795223   1.55268042 ...,  0.07879805 -0.80995796
 -0.56884822]


In [19]:
%time np.where(x<0, 0, x)  #1

Wall time: 12 ms


array([ 0.        ,  0.5795223 ,  1.55268042, ...,  0.07879805,
        0.        ,  0.        ])

In [28]:
def g(x):
    return 0 if x< 0 else x

g= np.vectorize(g)  #2 without loop

%time g(x)

Wall time: 208 ms


array([ 0.        ,  0.5795223 ,  1.55268042, ...,  0.07879805,
        0.        ,  0.        ])

In [26]:
def f(x):
    for i in range(len(x)):
        if x[i]<0:
            x[i]=0 
    print(x)  #3 with loop
%time f()
#%timeit print(x) #2 with loop

[ 0.          0.5795223   1.55268042 ...,  0.07879805  0.          0.        ]
Wall time: 240 ms


### Exercise 2

In [3]:
import numpy as np

def matrix(k):
    A=np.linspace(0, 4*k-1, 4*k)
    A.shape=(k, 4)
    return A.T

In [4]:
matrix(4)

array([[  0.,   4.,   8.,  12.],
       [  1.,   5.,   9.,  13.],
       [  2.,   6.,  10.,  14.],
       [  3.,   7.,  11.,  15.]])

### Exercise 3

In [6]:
def gcd(a,b, i):
    x, y= max(a,b), min(a,b)
    if i==0:
        print('0:gcd({0}, {1})'.format(x,y))
    c = x % y
    if c==0:
        return y
    else:
        print('{0}:gcd({1},{2})'.format(i+1,y,c))
        return gcd(y, c, i+1)
def lcm(a, b):
        return 'The least common multiple is: {0}'.format(a * b / gcd(a, b, 0))

In [9]:
gcd(123456,5790,0)

0:gcd(123456, 5790)
1:gcd(5790,1866)
2:gcd(1866,192)
3:gcd(192,138)
4:gcd(138,54)
5:gcd(54,30)
6:gcd(30,24)
7:gcd(24,6)


6

In [10]:
lcm(4,6)

0:gcd(6, 4)
1:gcd(4,2)


'The least common multiple is: 12.0'

### Exercise 4

In [13]:
import numpy as np

s='This     is for removing redundent spaces'
s.replace(' ','')

'Thisisforremovingredundentspaces'

In [11]:
l = 'This is      for removing       redundant spaces'
" ".join(l.split())

'This is for removing redundant spaces'

### Exercise 5

In [1]:
def f(x):
    return x % 3 == 0

l1 = [2, 18, 9, 22, 17, 24, 8, 12, 27]
A=list(filter(f,l1))
print(A)

[18, 9, 24, 12, 27]


### Exercise 6

In [5]:
import re
keep=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',' ',"'"]
stop_words=['to','a','as','this','for','in','on','but','--']
def normalize(s):
    result=''                       
    for c in s.lower():
        if c in keep:               #a,b,c,d,
            result+=c
    return result
def make_dict(s):
    words=re.split(' ',s)
    d={}
    for w in words:
        if w in d:
            d[w]+=1                 
        else:
            d[w]=1
    return d
def file_status(f):
    c=open(f).read()
    d=make_dict(c)
    lst=[(d[w],w) for w in d]
    lst.sort()
    lst.reverse()
    print('The 20 most frequent words from the text file are:')
    j=1
    for count,word in lst[:]:
        if word not in stop_words:
            print('%d.%4d %s'%(j,count,word))
            j+=1
        if j==21:
            break
#start_time=time.time()
file_status('Walden.txt')

The 20 most frequent words from the text file are:
1.6927 the
2.4474 and
3.3465 of
4.1905 I
5.1261 that
6.1252 is
7.1102 it
8.1008 not
9. 863 was
10. 854 or
11. 847 with
12. 834 which
13. 743 my
14. 715 be
15. 702 his
16. 660 have
17. 660 by
18. 642 are
19. 639 he
20. 605 at


### Exercise 7

In [6]:
import math
l = []
n = int(input('please input a number more than 2:'))
if n == 2:
    print('there is no prime less than 2!')
else:
    for a in range(2, n):
        for b in range(2, int(math.sqrt(a)) + 1):
            l.append(a % b)
        if 0 not in l:
            print(a)
        l = []

please input a number more than 2:100
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
