# Numpy

### Content 
* Numpy
    * Overview
    * Introduction to NumPy
    * NumPy Arrays
    * Operations on Arrays
    * Additional Functionality
    * Exercises

“Let’s be clear: the work of science has nothing whatever to do with consensus. Consensus is the business of politics. Science, on the contrary, requires only one investigator who happens to be right, which means that he or she has results that are verifiable by reference to the real world. In science consensus is irrelevant. What is relevant is reproducible results.” – Michael Crichton

### Overview
NumPy is a first-rate library for numerical programming    
    • Widely used in academia, finance and industry    
    • Mature, fast, stable and under continuous development    
In this lecture we introduce NumPy arrays and the fundamental array processing operations provided by NumPy

### Important Notes
We do of course assume that NumPy is installed on your machine    
Moreover, we’ll be using the new syntax A @ B for matrix multiplication, as opposed to the old syntax
np.dot(A, B)    
This will work if you’ve installed version Python 3.5 or later of Anaconda    
See this page for instructions on installing or updating your Anaconda distribution    

### References
• [The official NumPy documentation](https://docs.scipy.org/doc/numpy/reference/)

### Introduction to NumPy
The essential problem that NumPy solves is fast array processing    
For example, suppose we want to create an array of 1 million random draws from a uniform distribution and compute the mean    
If we did this in pure Python it would be orders of magnitude slower than C or Fortran    
This is because    
• Loops in Python over Python data types like lists carry significant overhead    
• C and Fortran code contains a lot of type information that can be used for optimization    
• Various optimizations can be carried out during compilation, when the compiler sees the instructions as a whole    
However, for a task like the one described above there’s no need to switch back to C or Fortran    
Instead we can use NumPy, where the instructions look like this:    

In [1]:
import numpy as np
x = np.random.uniform(0, 1, size=1000000)
x.mean()

0.4999479092100258

The operations of creating the array and computing its mean are both passed out to carefully optimized
machine code compiled from C    
More generally, NumPy sends operations in batches to optimized C and Fortran code    
This is similar in spirit to Matlab, which provides an interface to fast Fortran routines    

### A Comment on Vectorization
NumPy is great for operations that are naturally vectorized    
Vectorized operations are precompiled routines that can be sent in batches, like    
• matrix multiplication and other linear algebra routines    
• generating a vector of random numbers    
• applying a fixed transformation (e.g., sine or cosine) to an entire array    
In a later lecture we’ll discuss code that isn’t easy to vectorize and how such routines can also be optimized    

### NumPy Arrays
The most important thing that NumPy defines is an array data type formally called a numpy.ndarray    
NumPy arrays power a large proportion of the scientific Python ecosystem    
To create a NumPy array containing only zeros we use np.zeros    

In [2]:
import numpy as np
a = np.zeros(3)
a

array([ 0.,  0.,  0.])

In [3]:
type(a)

numpy.ndarray

NumPy arrays are somewhat like native Python lists, except that    
• Data must be homogeneous (all elements of the same type)    
• These types must be one of the data types (dtypes) provided by NumPy    
The most important of these dtypes are:    
• float64: 64 bit floating point number    
• int64: 64 bit integer    
• bool: 8 bit True or False    
There are also dtypes to represent complex numbers, unsigned integers, etc    
On modern machines, the default dtype for arrays is float64    

In [4]:
a = np.zeros(3)
type(a[0])

numpy.float64

If we want to use integers we can specify as follows:

In [5]:
a = np.zeros(3, dtype=int)
type(a[0])

numpy.int32

### Shape and Dimension

Consider the following assignment

In [6]:
z = np.zeros(10)

Here z is a flat array with no dimension—neither row nor column vector    
The dimension is recorded in the shape attribute, which is a tuple

In [8]:
z.shape # Note syntax for tuple with one element

(10,)

Here the shape tuple has only one element, which is the length of the array (tuples with one element end
with a comma)    
To give it dimension, we can change the shape attribute

In [9]:
z.shape = (10, 1)
z

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [10]:
z = np.zeros(4)
z.shape = (2, 2)
z

array([[ 0.,  0.],
       [ 0.,  0.]])

In the last case, to make the 2 by 2 array, we could also pass a tuple to the zeros() function, as in z =
np.zeros((2, 2))

### Creating Arrays

As we’ve seen, the np.zeros function creates an array of zeros    
You can probably guess what np.ones creates    
Related is np.empty, which creates arrays in memory that can later be populated with data    

In [11]:
z = np.empty(3)
z

array([ 0.,  0.,  0.])

The numbers you see here are garbage values    
(Python allocates 3 contiguous 64 bit pieces of memory, and the existing contents of those memory slots are interpreted as float64 values)    
To set up a grid of evenly spaced numbers use np.linspace

In [12]:
z = np.linspace(2, 4, 5) # From 2 to 4, with 5 elements

To create an identity matrix use either np.identity or np.eye

In [13]:
z = np.identity(2)
z

array([[ 1.,  0.],
       [ 0.,  1.]])

In addition, NumPy arrays can be created from Python lists, tuples, etc. using np.array

In [14]:
z = np.array([10, 20]) # ndarray from Python list
z

array([10, 20])

In [15]:
type(z)

numpy.ndarray

In [16]:
z = np.array((10, 20), dtype=float) # Here 'float' is equivalent to 'np.→float64'
z

array([ 10.,  20.])

In [17]:
z = np.array([[1, 2], [3, 4]]) # 2D array from a list of lists
z

array([[1, 2],
       [3, 4]])

See also np.asarray, which performs a similar function, but does not make a distinct copy of data already in a NumPy array

In [18]:
na = np.linspace(10, 20, 2)
na is np.asarray(na) # Does not copy NumPy arrays

True

In [19]:
na is np.array(na) # Does make a new copy --- perhaps unnecessarily

False

To read in the array data from a text file containing numeric data use np.loadtxt or np.genfromtxt—
see [the documentation](http://docs.scipy.org/doc/numpy/reference/routines.io.html) for details

### Array Indexing
For a flat array, indexing is the same as Python sequences:

In [20]:
z = np.linspace(1, 2, 5)
z

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [21]:
z[0]

1.0

In [22]:
z[0:2] # Two elements, starting at element 0

array([ 1.  ,  1.25])

In [23]:
z[-1]

2.0

For 2D arrays the index syntax is as follows:

In [24]:
z = np.array([[1, 2], [3, 4]])
z

array([[1, 2],
       [3, 4]])

In [25]:
z[0, 0]

1

In [26]:
z[0, 1]

2

And so on    
Note that indices are still zero-based, to maintain compatibility with Python sequences    
Columns and rows can be extracted as follows    

In [27]:
z[0,:]

array([1, 2])

In [28]:
z[:,1]

array([2, 4])

NumPy arrays of integers can also be used to extract elements

In [29]:
z = np.linspace(2, 4, 5)
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [30]:
indices = np.array((0, 2, 3))
z[indices]

array([ 2. ,  3. ,  3.5])

Finally, an array of dtype bool can be used to extract elements

In [31]:
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [32]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)
d

array([False,  True,  True, False, False], dtype=bool)

In [33]:
z[d]

array([ 2.5,  3. ])

We’ll see why this is useful below    
An aside: all elements of an array can be set equal to one number using slice notation

In [34]:
z = np.empty(3)
z

array([ 0.,  0.,  0.])

In [35]:
z[:] = 42
z

array([ 42.,  42.,  42.])

### Array Methods
Arrays have useful methods, all of which are carefully optimized

In [36]:
A = np.array((4, 3, 2, 1))
A

array([4, 3, 2, 1])

In [37]:
A.sort() # Sorts A in place
A

array([1, 2, 3, 4])

In [38]:
A.sum() # Sum

10

In [39]:
A.mean() # Mean

2.5

In [40]:
A.max() # Max

4

In [41]:
A.argmax() # Returns the index of the maximal element

3

In [42]:
A.cumsum() # Cumulative sum of the elements of A

array([ 1,  3,  6, 10], dtype=int32)

In [43]:
A.cumprod() # Cumulative product of the elements of A

array([ 1,  2,  6, 24], dtype=int32)

In [44]:
A.var() # Variance

1.25

In [45]:
A.std() # Standard deviation

1.1180339887498949

In [46]:
A.shape = (2, 2)
A.T # Equivalent to A.transpose()

array([[1, 3],
       [2, 4]])

Another method worth knowing is searchsorted()    
If z is a nondecreasing array, then z.searchsorted(a) returns the index of the first element of z that
is >= a

In [47]:
z = np.linspace(2, 4, 5)
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [48]:
z.searchsorted(2.2)

1

In [49]:
z.searchsorted(2.5)

1

In [50]:
z.searchsorted(2.6)

2

Many of the methods discussed above have equivalent functions in the NumPy namespace

In [51]:
a = np.array((4, 3, 2, 1))

In [52]:
np.sum(a)

10

In [53]:
np.mean(a)

2.5

## Operations on Arrays
### Algebraic Operations
The algebraic operators +, -, *, / and ** all act element-wise on arrays

In [54]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [55]:
a*b

array([ 5, 12, 21, 32])

We can add a scalar to each element as follows

In [56]:
a + 10

array([11, 12, 13, 14])

Scalar multiplication is similar

In [57]:
a * 10

array([10, 20, 30, 40])

The two dimensional arrays follow the same general rules

In [58]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A + B

array([[ 2.,  2.],
       [ 2.,  2.]])

In [59]:
A + 10

array([[ 11.,  11.],
       [ 11.,  11.]])

In [60]:
A * B

array([[ 1.,  1.],
       [ 1.,  1.]])

In particular, A * B is not the matrix product, it is an element-wise product
84    
### Matrix Multiplication
With Anaconda’s scientific Python package based around Python 3.5 and above, one can use the @ symbol
for matrix multiplication, as follows:    

In [61]:
import numpy as np
A = np.ones((2, 2))
B = np.ones((2, 2))
A @ B

array([[ 2.,  2.],
       [ 2.,  2.]])

(For older versions of Python and NumPy you need to use the np.dot function)    
We can also use @ to take the inner product of two flat arrays

In [63]:
A = np.array((1, 2))
B = np.array((10, 20))
A @ B

50

In fact, we can use @ when one element is a Python list or tuple    

In [65]:
A = np.array(((1, 2), (3, 4)))
A

array([[1, 2],
       [3, 4]])

In [66]:
A @ (0, 1)

array([2, 4])

Since we are postmultiplying, the tuple is treated as a column vector    
### Mutability and Copying Arrays
NumPy arrays are mutable data types, like Python lists    
In other words, their contents can be altered (mutated) in memory after initialization    
We already saw examples above    
Here’s another example:    

In [67]:
a = np.array([42, 44])
a

array([42, 44])

In [68]:
a[-1] = 0 # Change last element to 0
a

array([42,  0])

Mutability leads to the following behavior (which causes a surprising amount of outrage in classes that
we’ve taught)

In [69]:
a = np.random.randn(3)
a

array([-0.19508819, -0.53336513,  0.49001478])

In [70]:
b = a
b[0] = 0.0
a

array([ 0.        , -0.53336513,  0.49001478])

What’s happened is that we have changed a by changing b    
The name b is bound to a and becomes just another reference to the array (the Python assignment model is described in more detail later in the course)    
Hence, it has equal rights to make changes to that array    
This is in fact the most sensible default behavior    
It means that we pass around only pointers to data, rather than making copies    
Making copies is expensive in terms of both speed and memory    
### Making Copies
It is of course possible to make b an independent copy of a when required    
With recent versions of NumPy, this is best done using np.copyto    

In [71]:
a = np.random.randn(3)
a

array([ 1.09755677, -0.1922895 , -0.3566036 ])

In [72]:
b = np.empty_like(a) # empty array with same shape as a
np.copyto(b, a) # copy to b from a
b

array([ 1.09755677, -0.1922895 , -0.3566036 ])

Now b is an independent copy (often called a deep copy)

In [73]:
b[:] = 1
b

array([ 1.,  1.,  1.])

In [74]:
a

array([ 1.09755677, -0.1922895 , -0.3566036 ])

Note that the change to b has not affected a    
### Additional Functionality
Let’s look at some other useful things we can do with NumPy    
### Vectorized Functions
NumPy provides versions of the standard functions log, exp, sin, etc. that act element-wise on arrays    

In [75]:
z = np.array([1, 2, 3])
np.sin(z)

array([ 0.84147098,  0.90929743,  0.14112001])

This eliminates the need for explicit element-by-element loops such as

In [76]:
n = len(z)
y = np.empty(n)
for i in range(n):
    y[i] = np.sin(z[i])

Because they act element-wise on arrays, these functions are called vectorized functions    
In NumPy-speak, they are also called ufuncs, which stands for “universal functions”    
As we saw above, the usual arithmetic operations (+, *, etc.) also work element-wise, and combining these with the ufuncs gives a very large set of fast element-wise functions

In [77]:
z

array([1, 2, 3])

In [78]:
(1 / np.sqrt(2 * np.pi)) * np.exp(- 0.5 * z**2)

array([ 0.24197072,  0.05399097,  0.00443185])

Not all user defined functions will act element-wise    
For example, passing the function f defined below a NumPy array causes a ValueError

In [79]:
def f(x):
    return 1 if x > 0 else 0

The NumPy function np.where provides a vectorized alternative:

In [80]:
import numpy as np

x = np.random.randn(4)
x

array([-0.25925175,  1.13746983,  0.16792831, -0.7429076 ])

In [81]:
np.where(x > 0, 1, 0) # Insert 1 if x > 0 true, otherwise 0

array([0, 1, 1, 0])

You can also use np.vectorize to vectorize a given function

In [82]:
def f(x): return 1 if x > 0 else 0
f = np.vectorize(f)
f(x)      # Passing the same vector x as in the previous example

array([0, 1, 1, 0])

However, this approach doesn’t always obtain the same speed as a more carefully crafted vectorized function    
### Comparisons
As a rule, comparisons on arrays are done element-wise    

In [83]:
z = np.array([2, 3])
y = np.array([2, 3])
z == y

array([ True,  True], dtype=bool)

In [84]:
y[0] = 5
z == y

array([False,  True], dtype=bool)

In [85]:
z != y

array([ True, False], dtype=bool)

The situation is similar for >, <, >= and <=    
We can also do comparisons against scalars

In [86]:
z = np.linspace(0, 10, 5)
z

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [87]:
z > 3

array([False, False,  True,  True,  True], dtype=bool)

This is particularly useful for conditional extraction

In [88]:
b = z > 3
b

array([False, False,  True,  True,  True], dtype=bool)

In [89]:
z[b]

array([  5. ,   7.5,  10. ])

Of course we can—and frequently do—perform this in one step

In [90]:
z[z > 3]

array([  5. ,   7.5,  10. ])

### Subpackages
NumPy provides some additional functionality related to scientific programming through its subpackages    
We’ve already seen how we can generate random variables using np.random    

In [91]:
z = np.random.randn(10000) # Generate standard normals
y = np.random.binomial(10, 0.5, size=1000) # 1,000 draws from Bin(10, 0.5)
y.mean()

5.0090000000000003

Another commonly used subpackage is np.linalg

In [92]:
A = np.array([[1, 2], [3, 4]])
np.linalg.det(A) # Compute the determinant

-2.0000000000000004

In [93]:
np.linalg.inv(A) # Compute the inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Much of this functionality is also available in [SciPy](https://www.scipy.org/), a collection of modules that are built on top of NumPy    
We’ll cover the SciPy versions in more detail soon    
For a comprehensive list of what’s available in NumPy see [this documentation](https://docs.scipy.org/doc/numpy/reference/routines.html)    
## Exercises
### Exercise 1
Consider the polynomial expression
$$p(x) = a_0+a_1x + a_2x^2 + \cdots + a_Nx^N = \sum_{n=N}^n a_nx^n$$
Earlier, you wrote a simple function p(x, coeff) to evaluate (1.2) without considering efficiency    
Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop    
(Such functionality is already implemented as np.poly1d, but for the sake of the exercise don’t use this class)    
• Hint: Use np.cumprod()    

In [ ]:
# Exercise 1

def p(x, coef):
    X = np.empty(len(coef))
    X[0] = 1
    X[1:] = x
    y = np.cumprod(X)  
    return coef @ y

### Exercise 2
Let q be a NumPy array of length n with q.sum() == 1    
Suppose that q represents a probability mass function    
We wish to generate a discrete random variable 𝑥 such that P{𝑥 = 𝑖} = $𝑞_𝑖$     
In other words, x takes values in range(len(q)) and x = i with probability q[i]    
The standard (inverse transform) algorithm is as follows:    
• Divide the unit interval [0, 1] into 𝑛 subintervals $𝐼_0, 𝐼_1, . . . , 𝐼_{𝑛−1}$ such that the length of $𝐼_𝑖 $is $𝑞_𝑖$    
• Draw a uniform random variable 𝑈 on [0, 1] and return the 𝑖 such that 𝑈 ∈ $𝐼_𝑖 $    
The probability of drawing 𝑖 is the length of$𝐼_𝑖 $, which is equal to  $𝑞_𝑖$     
We can implement the algorithm as follows

In [95]:
from random import uniform
def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]

In [ ]:
# Exercise 2

from numpy import cumsum
from numpy.random import uniform

class discreteRV:
    
    def __init__(self, q):

        self.q = q
        self.Q = cumsum(q)

    def draw(self, k=1):

        return self.Q.searchsorted(uniform(0, 1, size=k))

If you can’t see how this works, try thinking through the flow for a simple example, such as q = [0.25, 0.75] It helps to sketch the intervals on paper    
Your exercise is to speed it up using NumPy, avoiding explicit loops    
• Hint: Use np.searchsorted and np.cumsum
If you can, implement the functionality as a class called discreteRV, where    
• the data for an instance of the class is the vector of probabilities q
• the class has a draw() method, which returns one draw according to the algorithm described above    
If you can, write the method so that draw(k) returns k draws from q   
### Exercise 3
Recall our [earlier discussion](https://lectures.quantecon.org/py/python_oop.html#id8) of the empirical cumulative distribution function    
Your task is to    
1. Make the $__call__$ method more efficient using NumPy    
2. Add a method that plots the ECDF over [𝑎, 𝑏], where 𝑎 and 𝑏 are method parameters

### Exercise 4
 Using Array methods to calculate the variance of array (1,2,3,4,5) by definition, and compare your result with the function of variance.
### Exercise 5
Generate three 2×2 matrices A,B,C, of which the elements are from standard normal distribution, N(0,1). Then confirm following laws:
1. Associative law: (AB)C=A(BC)
2. Reverse order law: $(AB)^T=B^T A^T$


In [ ]:
# Exercise 3

class ECDF:

    def __init__(self, observations):
        self.observations = np.asarray(observations)

    def __call__(self, x):

        return np.mean(self.observations <= x)

    def plot(self, a=None, b=None):

        # === choose reasonable interval if [a, b] not specified === #
        if a is None:
            a = self.observations.min() - self.observations.std()
        if b is None:
            b = self.observations.max() + self.observations.std()

        # === generate plot === #
        x_vals = np.linspace(a, b, num=100)
        f = np.vectorize(self.__call__)
        plt.plot(x_vals, f(x_vals))
        plt.show()

In [4]:
# Exercise 4

import numpy as np
x = np.array([1, 2, 3, 4, 5])
var_x = np.mean((x - np.mean(x))**2)
var_x

2.0

In [5]:
np.var(x)

2.0

In [14]:
# Exercise 5

A = np.random.randn(3, 2, 2)
(A[0,:,:]@A[1,:,:])@A[2,:,:]

array([[-0.05381599, -0.38852621],
       [ 0.4688516 ,  0.92313944]])

In [15]:
A[0,:,:]@(A[1,:,:]@A[2,:,:])

array([[-0.05381599, -0.38852621],
       [ 0.4688516 ,  0.92313944]])

In [16]:
(A[0,:,:]@A[1,:,:]).T

array([[-0.1901325 ,  0.36414603],
       [ 0.08336983, -0.60833093]])

In [18]:
A[1,:,:].T@A[0,:,:].T

array([[-0.1901325 ,  0.36414603],
       [ 0.08336983, -0.60833093]])

### Exercise 6
a = np.random.uniform(0,1, (3, 3)).    
Make an independent copy and dependent copy of a. What’s the difference between the two copies?

In [33]:
# Exercise 6

b = a
b

array([[ 0.57686219,  0.91512376,  0.76925829],
       [ 0.54117285,  0.06226271,  0.55362865],
       [ 0.54999371,  0.65503516,  0.20142404]])

In [34]:
a[0, 0] = 1
b

array([[ 1.        ,  0.91512376,  0.76925829],
       [ 0.54117285,  0.06226271,  0.55362865],
       [ 0.54999371,  0.65503516,  0.20142404]])

In [37]:
a = np.random.uniform(0,1, (3, 3))

In [38]:
b = a.copy()
b

array([[ 0.93608831,  0.0881178 ,  0.76942617],
       [ 0.39165493,  0.93408514,  0.20428188],
       [ 0.33253136,  0.91881405,  0.90391203]])

In [39]:
a[0, 0] = 1
b

array([[ 0.93608831,  0.0881178 ,  0.76942617],
       [ 0.39165493,  0.93408514,  0.20428188],
       [ 0.33253136,  0.91881405,  0.90391203]])

### Exercise 7
Calculate the values of $sin⁡(x)^2$, when $x = π/100, π/99, π/98, … , π/5, π/4, π/3, π/2, π$. And then calculate the corresponding values of $cos⁡(x)^2$.     
Hint: Use the data type of numpy.ndarray. 

In [25]:
# Exercise 7

π = np.pi

sin_2 = np.empty(100)
cos_2 = np.empty(100)

for i in range(99):
    x = np.array([π / (i+1)])
    sin_2[i], cos_2[i] = (np.sin(x))**2, (np.cos(x))**2

### Exercise 8
Note that not all user defined functions will act element-wise on arrays. Here is an example.     
Type the following code.See what happens, and then try to fix it. 

In [30]:
# Exercise 8

import numpy as np
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
def f(x):
    B = np.empty(len(x))
    for i, j in enumerate(x):
        if j % 5 == 0:
            B[i] = 1
        else:
            B[i] = 0
    return B

f(A)

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.])