In [1]:
#Exercise 1 Part 1
#using loop
import numpy as np
def gen_rvs_by_loop(n):
    rvs = np.arange(n)
    for i in range(n):
        rvs[i] = np.random.rand()
    return rvs
%time gen_rvs_by_loop(10000000)

Wall time: 2.85 s


array([0, 0, 0, ..., 0, 0, 0])

In [2]:
#Exercise 1 Part 2
#without loop
#using np.random.randn()
import numpy as np
%time rvs = np.random.randn(10000000)

Wall time: 312 ms


In [3]:
#Exercise 1 Part 3
#without loop
#using scipy.stats.norm
from scipy.stats import norm
%time rvs = norm.rvs(loc=0,scale=1,size=10000000)

Wall time: 370 ms


In [4]:
#Exercise 2
import numpy as np
def gen_matrix(k):
    fst_row = 4*np.arange(k)
    return np.vstack((fst_row,fst_row+1,fst_row+2,fst_row+3))

#Test
gen_matrix(4)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [5]:
#Exercise 3 Part 1
#compute the Greatest Common Divisor with the method of successive division

def gcd(a,b,count_flag=True,print_flag=True):
#If count_flag=True, we inialize the global variable "cnt" to 0
#If print_Flag=True, present the computing process and vice versa 
#The global variable "cnt" records how many times the recursion occurs
    global cnt                
    if count_flag==True:
        cnt = 0
    lhs = max(a,b)
    rhs = min(a,b)
    remainder = lhs%rhs
    if print_flag==True:
        print('{0}:gcd({1},{2})'.format(cnt,lhs,rhs))
    if remainder == 0:
        return rhs
    else:
        cnt+=1
        return gcd(rhs,remainder,count_flag=False,print_flag=print_flag)
    
#Test
gcd(123456,7890)

0:gcd(123456,7890)
1:gcd(7890,5106)
2:gcd(5106,2784)
3:gcd(2784,2322)
4:gcd(2322,462)
5:gcd(462,12)
6:gcd(12,6)


6

In [6]:
#Exercise 3 Part 2
#compute the Least Common Multiple by considering its relationship with the Greatest Common Divisor
def lcm(a,b):
    return a*b/gcd(a,b,print_flag=False) #For simplicity,we omit the printing process

#Test
lcm(3,4)

12.0

In [7]:
#Exercise 4
import re
def remove_redundant_spaces(s):
    return re.sub('\s{2,}',chr(32),s)

#Test
remove_redundant_spaces('This is    for removing redundant spaces')

'This is for removing redundant spaces'

In [8]:
#Exercise 5
import numpy as np
def n_multiples_subarray(lst,n):
    arr = np.asarray(lst)
    return arr[arr%n==0]

#Test
n_multiples_subarray([2, 18, 9, 22, 17, 24, 8, 12, 27],3)

array([18,  9, 24, 12, 27])

In [9]:
#Exercise 6
import re
import pandas as pd

#obtain contents from Walden.txt
with open('Walden.txt') as f:
    content = f.read()

#only keep English words and delete others 
content = re.sub('[^a-zA-z]',chr(32),content)  #substitute punctuations with spaces
content = re.sub('\s{2,}',chr(32),content)     #remove redundant spaces 

#split the whole text into words
content = content.split(' ')

#obtain stop words from StopWords.txt
#The table of stop words is downloaded from http://blog.csdn.net/shijiebei2009/article/details/39696523
with open('StopWords.txt') as f:
    words = f.readlines()
stop_words = []
for word in words:
    word = word.strip()
    stop_words.append(word)

#All words in StopWords.txt are in lower case
#So we change the words in "content" into lower case in preparation for comparison 
content_lower = []
for word in content:
    content_lower.append(word.lower())
content_set = set(content_lower)
content_set = content_set-set(stop_words) #delete all the stop words from "content_set"
content_list = list(content_set)

#compute words' frequency in content_set
word_frequency = []
for word in content_set:
    f = content.count(word)
    word_frequency.append(f)

#generate a dictionary containing words and their frequency
content_dict = dict(zip(content_list,word_frequency))

#put all the data into a pandas series, so that we can process data and present results in a more convenient way
df = pd.Series(content_dict)
df = df.sort_values(ascending=False) #put word's frequency in descending order

#Present 20 most frequent words
df[0:20]

life       206
day        201
house      195
water      178
time       173
pond       165
woods      148
ice        121
heard      103
live       103
winter      98
shore       90
morning     88
feet        84
night       83
half        82
sun         81
earth       80
spring      76
surface     73
dtype: int64

In [10]:
#Exercise 7
#Using the algorithm designed by Eeatosthese, whose main idea is as follows:
#Once a prime number is found, all of its multiples are composite numbers.
#With this idea, we can process several numbers in the same time

import numpy as np

def find_prime_numbers(N):
    flag_set = np.ones(N)
    flag_set[0] = 0
    numbers = np.arange(1,N+1)
    for i in range(N):
        if flag_set[i]==1:
            flag_set[numbers%numbers[i]==0]=0
            flag_set[i] = 1
    return numbers[flag_set==1]

%time a = find_prime_numbers(100000)

Wall time: 4.65 s
